export const siteUrl = "https://www.buildunix.com";
export const companyEmail = "info@buildunix.com";

export const siteMetadata = {
  name: "BuildUNIX",
  shortName: "BuildUNIX",
  tagline: "Digitizing Construction Execution",
  homeTitle: "BuildUNIX \u2014 Construction Execution Platform for Indian PMC Firms",
  homeDescription:
    "BuildUNIX is a phase-enforced construction operating system. Mandatory photo documentation, real-time heatmaps, AI daily reports, and formal snag tracking. Built for PMC firms in India.",
  homeOgTitle: "BuildUNIX \u2014 Digitizing Construction Execution",
  aboutTitle: "Why Use BuildUNIX \u2014 Built for Indian PMC Firms",
  aboutDescription:
    "Why PMC-led projects choose BuildUNIX: hard-gated phase sequencing, tamper-proof photo evidence, formal snag tracking, live heatmaps, and AI daily reporting.",
  contactTitle: "Book a Demo \u2014 BuildUNIX Construction Platform",
  contactDescription:
    "Book a 30-minute demo and see BuildUNIX running on an active construction project. No pressure. Just a real walkthrough."
};

export const navLinks = [
  { label: "Product", href: "/#features" },
  { label: "How It Works", href: "/#how-it-works" },
  { label: "Why BuildUnix", href: "/about" },
  { label: "Contact", href: "/contact" }
];

export const heroContent = {
  eyebrow: "Construction Execution Platform \u00B7 India",
  headlineLead: "Construction runs on",
  initialHeadlineTail: "WhatsApp and chaos.",
  finalHeadlineTail: "BuildUNIX changes that.",
  subheadline:
    "A phase-enforced construction operating system built for Indian PMC firms. Mandatory photo documentation. Real-time progress heatmaps. AI-generated daily reports. PMC approval is the only unlock trigger.",
  primaryCta: "Book a Free Demo",
  secondaryCta: "See How It Works",
  proof:
    "Piloted on a \u20B91,200 Cr site in Hyderabad \u00B7 Built for PMC firms, contractors, and developers"
};

export const problemStats = [
  {
    value: "\u20B92-5 L",
    accent: true,
    label: "average cost of a single rework incident due to sequencing errors."
  },
  {
    value: "0 Checks",
    accent: false,
    label: "when critical work sequences are decided by an unrecorded phone call."
  },
  {
    value: "9:00 PM",
    accent: true,
    label: "when BuildUnix delivers your AI site report \u2014 fully automated."
  }
];

export const phaseNames = [
  "Footings",
  "Plinth Beam",
  "Columns",
  "Lift Wall",
  "Staircase (Structural)",
  "Slab",
  "Terrace RCC Activities",
  "Flat Finishing",
  "External Finishing",
  "Corridors Finishing",
  "Basements & Stilt Finishing",
  "Staircase Finishing",
  "Lift Finishing",
  "Terrace Finishing"
];

export const howItWorksSteps = [
  {
    id: "structure",
    label: "Step 1",
    title: "Everything starts with structure.",
    body:
      "Create your project, add blocks, and BuildUnix auto-loads 14 construction phases with pre-configured dependency logic. No setup headache. No missed phases.",
    visual: "structure"
  },
  {
    id: "upload",
    label: "Step 2",
    title: "Native camera documentation.",
    body:
      "Every subphase requires Pre, During, and Post photos captured from the native camera on-site. Gallery uploads are hard-blocked. GPS, UTC timestamp, SHA-256 hash, and identity are embedded instantly.",
    visual: "upload"
  },
  {
    id: "verify",
    label: "Step 3",
    title: "PMC Engineers hold the keys.",
    body:
      "When work is submitted, the PMC Engineer is notified. They inspect the tamper-proof photos. One tap to approve \u2014 or raise a formal snag. No subphase can be skipped.",
    visual: "verify"
  },
  {
    id: "track",
    label: "Step 4",
    title: "Management sees everything, live.",
    body:
      "A live color-coded heatmap shows the status of every phase across every block. Grey is locked. Yellow is uploading. Blue is awaiting PMC. Green is approved. Red is a snag. Updated in under 2 seconds.",
    visual: "track"
  },
  {
    id: "report",
    label: "Step 5",
    title: "AI writes your daily report.",
    body:
      "A full narrative PDF \u2014 timeline, gallery, snag summary, and completion stats \u2014 is generated by AI and delivered automatically at 9 PM. Zero manual input.",
    visual: "report"
  }
];

export const featureCards = [
  {
    title: "Dependency Engine",
    icon: "flow",
    description:
      "14 phases with 6 logic types: Sequential, Parallel, Merge, Independent, Nested, and Final Parallel Check. Hard gates, not suggestions."
  },
  {
    title: "Tamper-Proof Docs",
    icon: "camera",
    description:
      "Pre, During, and Post slots. Native camera only. Every photo embeds GPS, UTC timestamp, and a verifiable SHA-256 cryptographic hash."
  },
  {
    title: "Four-Type Snags",
    icon: "snag",
    description:
      "PMC, Safety, MEP, and Client QC snags. PMC snags block workflow. Safety and MEP snags block final phase completion. Full resolution threads."
  },
  {
    title: "Live Heatmap",
    icon: "heatmap",
    description:
      "A color-coded grid updates within 2 seconds of every action. Drill from company to project, block, phase, and subphase without losing context."
  },
  {
    title: "AI Daily Reports",
    icon: "report",
    description:
      "Structured PDF narratives generated at 9 PM with a chronological timeline, photo gallery, snag summary, progress metrics, and flagged items."
  },
  {
    title: "Offline Field Mode",
    icon: "offline",
    description:
      "Photos and metadata queue securely on-device, then sync in chronological order after reconnect. Supports high-volume offline capture in live site conditions."
  }
];

export const roles = [
  {
    id: "pmc",
    label: "PMC Engineer",
    title: "PMC Engineer",
    device: "mobile",
    summary: "The only role that can approve work and unlock the next phase.",
    actions: [
      "Receives push notifications when contractors submit work.",
      "Reviews Pre, During, and Post photos with GPS, time, and identity overlays.",
      "Approves work or raises a formal PMC snag that blocks progression.",
      "Closes snags from Client QC, Safety, and MEP teams."
    ],
    cannot: "Cannot upload construction photos, manage users, or modify templates.",
    previewTitle: "Awaiting inspection",
    previewItems: [
      "Slab Layout \u00B7 Floor 3",
      "Column RCC Steel \u00B7 Flat A402",
      "Lift Wall RCC Post \u00B7 Floor 9"
    ]
  },
  {
    id: "contractor",
    label: "Contractor",
    title: "Contractor Engineer",
    device: "mobile",
    summary: "Built for field execution. Capture work, submit evidence, resolve snags.",
    actions: [
      "Uploads Pre, During, and Post photos from the native camera only.",
      "Sees locked subphases clearly before PMC unlocks them.",
      "Submits for verification once required slots are complete.",
      "Uploads resolution evidence when snag threads return to site."
    ],
    cannot: "Cannot approve work, skip subphases, or access unassigned scope.",
    previewTitle: "Photo documentation",
    previewItems: [
      "Pre photo complete",
      "During photo complete",
      "Post photo pending"
    ]
  },
  {
    id: "pm",
    label: "Project Manager",
    title: "Project Manager",
    device: "desktop",
    summary: "A live command center for progress, risk, and accountability across the entire site.",
    actions: [
      "Sees real-time heatmaps across blocks, phases, and units.",
      "Browses all photos, snag threads, and AI daily reports.",
      "Comments directly on any photo for field teams to see.",
      "Tracks progress and escalation points without calling site for updates."
    ],
    cannot: "Cannot approve work, upload construction evidence, or close snags.",
    previewTitle: "Portfolio overview",
    previewItems: [
      "Tower A \u00B7 63% complete",
      "12 open snags",
      "Tonight's report queued"
    ]
  },
  {
    id: "client-qc",
    label: "Client QC",
    title: "Client QC",
    device: "mobile",
    summary: "Assigned subphase-level visibility with a formal path to raise quality concerns.",
    actions: [
      "Views photos and metadata on assigned subphases only.",
      "Raises Client QC snags at any time with photo evidence.",
      "Tracks PMC comments and closure updates in the same thread.",
      "Sees Safety and MEP snag threads in read-only mode."
    ],
    cannot: "Cannot unlock work, close snags, or access unassigned subphases.",
    previewTitle: "Quality review",
    previewItems: [
      "Snag raised \u00B7 grout finish mismatch",
      "PMC reviewing resolution",
      "2 assigned units today"
    ]
  },
  {
    id: "safety-mep",
    label: "Safety & MEP",
    title: "Safety & MEP Users",
    device: "mobile",
    summary: "Department-level visibility across assigned blocks or phases, even after PMC completion.",
    actions: [
      "Raises Safety or MEP snags on any accessible subphase at any time.",
      "Sees department-wide open issues so nothing gets missed.",
      "Keeps final phase completion blocked until unresolved issues are closed.",
      "Works from a shared view across all users in the department."
    ],
    cannot: "Cannot approve work or upload construction execution photos.",
    previewTitle: "Department watchlist",
    previewItems: [
      "Electrical shaft guardrail missing",
      "Open MEP clearance \u00B7 Floor 7",
      "Completed subphase still reviewable"
    ]
  },
  {
    id: "company-admin",
    label: "Company Admin",
    title: "Company Admin",
    device: "desktop",
    summary: "Executive read-only visibility across every project under the company.",
    actions: [
      "Sees completion, snag trends, and report history across projects.",
      "Reviews contractor scorecards and overdue issue summaries.",
      "Opens live heatmaps without asking teams for manual updates.",
      "Receives AI daily reports as a configured recipient."
    ],
    cannot: "Cannot edit workflows, approvals, assignments, or project templates.",
    previewTitle: "Company dashboard",
    previewItems: [
      "4 active projects",
      "18 overdue snags",
      "2 reports delivered today"
    ]
  }
];

export const trustColumns = [
  {
    title: "The Financial Case",
    body:
      "Rework incidents on Indian construction sites routinely cost \u20B92-5 lakh per occurrence. BuildUnix prevents the sequencing errors that cause them. Payback period: under 90 days."
  },
  {
    title: "The Accountability Model",
    body:
      "Every photo is GPS-tagged, timestamped to the second of capture, and signed with the uploader's identity. Every approval is logged. Every snag has a thread. Nothing is verbal. Nothing is deniable."
  },
  {
    title: "The AI Intelligence Layer",
    body:
      "At 9 PM every evening, a full AI-generated narrative site report is delivered automatically to Project Managers and configured stakeholders. Chronological activity log. Photo gallery. Snag summary. Zero manual effort."
  }
];

export const statBarItems = [
  { value: 14, label: "Construction Phases" },
  { value: 7, label: "User Roles" },
  { value: 6, label: "Dependency Types" },
  { value: 0, prefix: "\u20B9", label: "Manual Reporting Cost" },
  { value: 2, prefix: "< ", label: "sec Real-Time Sync" }
];

export const whyBuildUnixReasons = [
  {
    title: "Sequencing errors become impossible",
    body:
      "The dependency engine hard-gates every subphase. If the required predecessor is not PMC-approved, the next step stays locked. No workaround. No verbal override."
  },
  {
    title: "Every milestone has real evidence",
    body:
      "Pre, During, and Post photos are mandatory. Native camera only. Every image carries GPS coordinates, UTC timestamp, user identity, and a SHA-256 integrity hash."
  },
  {
    title: "PMC approvals move faster",
    body:
      "When contractors submit work, PMC Engineers get an instant notification and can inspect photo evidence in real time instead of waiting for the next physical site visit."
  },
  {
    title: "Defects become formal workflows",
    body:
      "PMC, Safety, MEP, and Client QC issues are raised as structured snag tickets with threaded evidence and mandatory resolution photos instead of disappearing into calls and chats."
  },
  {
    title: "Management sees the site live",
    body:
      "Color-coded heatmaps show every phase, block, and subphase in real time. Teams stop relying on screenshots, weekly calls, and reactive escalation."
  },
  {
    title: "Reporting happens automatically",
    body:
      "At 9 PM, BuildUnix generates a narrative PDF with site activity, photos, progress, open snags, and flagged anomalies. No one has to manually compile the day."
  }
];

export const whyBuildUnixStats = [
  {
    value: "\u20B92-5 L",
    label: "rework cost avoided per incident when sequencing errors are prevented"
  },
  {
    value: "<90 Days",
    label: "payback period for subscribing firms, based on the investor guide"
  },
  {
    value: "128+",
    label: "subphases tracked across the built-in 14-phase construction template"
  },
  {
    value: "<2 sec",
    label: "real-time heatmap update latency for live site visibility"
  }
];

export const whyBuildUnixFit = [
  {
    title: "Built for PMC-led projects",
    body:
      "The system is strongest on projects where PMC approval is already the operational truth but the enforcement and evidence trail are missing."
  },
  {
    title: "Designed for multi-block execution",
    body:
      "It fits sites with multiple towers, simultaneous trades, and many active subphases where WhatsApp coordination breaks down fastest."
  },
  {
    title: "Ready for Indian site reality",
    body:
      "Offline capture, sunlight-readable mobile flows, and built-in Indian construction phase coverage make it practical on actual sites, not just in demos."
  }
];

export const whyBuildUnixMoat = [
  {
    title: "14-phase India-native template",
    body:
      "The platform is pre-configured for Indian residential construction rather than asking teams to rebuild their workflow inside a generic Western SaaS tool."
  },
  {
    title: "6-type dependency engine",
    body:
      "Sequential, Parallel, Merge, Independent, Nested Sequential, and Final Parallel Check logic allow real construction sequencing to be enforced instead of merely tracked."
  },
  {
    title: "Daily compliance record by default",
    body:
      "The audit trail grows automatically: approvals, photos, snags, comments, and AI reports accumulate into a defensible project record that gets more valuable over time."
  }
];

export const contactReasons = [
  {
    title: "See the dependency engine live",
    body:
      "Watch how 14 construction phases enforce sequencing with real PMC approval gates and real snag flows."
  },
  {
    title: "Understand the financial case",
    body:
      "We'll walk you through exactly how BuildUnix prevents the \u20B92-5 lakh rework incidents that PMC firms currently absorb."
  },
  {
    title: "See your role's interface",
    body:
      "Whether you're a PMC Engineer, Project Manager, or Developer, we'll show you exactly what your team will see."
  },
  {
    title: "Piloted on a \u20B91,200 Cr site",
    body:
      "BuildUnix isn't theoretical. It was designed for and tested against a major Hyderabad construction project."
  }
];

export const formOptions = {
  roles: [
    "PMC Engineer",
    "Project Manager",
    "Developer",
    "Contractor",
    "Other"
  ],
  projectSizes: [
    "Under \u20B950 Cr",
    "\u20B950-200 Cr",
    "\u20B9200-500 Cr",
    "\u20B9500 Cr+",
    "Not sure"
  ]
};

export const footerColumns = [
  {
    title: "Product",
    links: [
      { label: "How It Works", href: "/#how-it-works" },
      { label: "Features", href: "/#features" },
      { label: "Why BuildUnix", href: "/about" },
      { label: "Contact", href: "/contact" }
    ]
  },
  {
    title: "Company",
    links: [
      { label: "Why BuildUnix", href: "/about" },
      {
        label: "Privacy Policy",
        href: `mailto:${companyEmail}?subject=BuildUnix%20Privacy%20Policy`
      }
    ]
  },
  {
    title: "Contact",
    links: [
      { label: companyEmail, href: `mailto:${companyEmail}` },
      { label: "Book a Demo", href: "/contact" }
    ]
  }
];
